---

- hosts: all
  tasks:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600
    become: yes

  - name: Install packages
    apt:
      name:
        - build-essential
        - git
        - python-dev
        - python-pip
        - scons
        - swig
        - vim
    become: yes

  - name: Create RPi PWM library directory
    file:
      path: /opt/rpi_ws281x
      state: directory
      owner: pi
      group: pi
      mode: 0775
    become: yes

  - name: Clone Raspberry Pi PWM library for WS281X LEDs
    git:
      repo: 'https://github.com/jgarff/rpi_ws281x.git'
      dest: /opt/rpi_ws281x
      update: yes

  - name: Configure Neopixel support
    shell: scons
    args:
      chdir: /opt/rpi_ws281x
    become: yes

  - name: Install Neopixel Python module
    shell: python setup.py install
    args:
      chdir: /opt/rpi_ws281x/python
    become: yes

  - pip:
      name: Flask
    become: yes

  - pip:
      name: watchdog
    become: yes

  - template:
      src: templates/pi_web_listener.j2
      dest: /lib/systemd/system/pi-web-listener.service
      owner: root
      group: root
      mode: 644

  - template:
      src: templates/pi_file_listener.j2
      dest: /lib/systemd/system/pi-file-listener.service
      owner: root
      group: root
      mode: 644

  - name: Create domestics directory
    file:
      path: /opt/domestics
      state: directory
      owner: pi
      group: pi
      mode: 0775
    become: yes

  - name: Clone domestics
    git:
      repo: git@github.com:ericgross/domestics.git
      dest: /opt/domestics
      update: yes

  - name: Restart pi-file-listener
    systemd:
      state: restarted
      daemon_reload: yes
      name: pi-file-listener
      enabled: true
    become: yes

  - name: Restart pi-web-listener
    systemd:
      state: restarted
      daemon_reload: yes
      name: pi-web-listener
      enabled: true
    become: yes
