---

- hosts: all
  become: yes
  tasks:
  - name: Update all packages to the latest version
    apt:
      upgrade: dist
      update_cache: yes
      cache_valid_time: 3600

  - name: Install packages
    apt:
      name:
        - build-essential
        - git
        - python-dev
        - python-pip
        - scons
        - swig
        - vim

  - name: Clone Raspberry Pi PWM library for WS281X LEDs
    git:
      repo: 'https://github.com/jgarff/rpi_ws281x.git'
      dest: /opt/rpi_ws281x
      update: yes

  - name: Configure Neopixel support
    shell: scons
    args:
      chdir: /opt/rpi_ws281x

  - name: Install Neopixel Python module
    shell: python setup.py install
    args:
      chdir: /opt/rpi_ws281x/python

  - pip:
      name: Flask

  - pip:
      name: apscheduler

  - template:
      src: templates/pi_listener.j2
      dest: /lib/systemd/system/pi-listener.service
      owner: root
      group: root
      mode: 644

  - name: Clone domestics
    git:
      repo: https://github.com/ericgross/domestics.git
      dest: /opt/domestics
      update: yes

  - name: Restart pi-listener
    systemd:
      state: restarted
      daemon_reload: yes
      name: pi-listener
